name: Add new mod / edit existing mod
description: Request for a new mod to be added to the database, or edit an existing mod.
title: "[Nome do Mod aqui]"
labels: ["add-mod"]
body:
  - type: input
    id: uniqueName
    attributes:
      label: Nome único do mod
      description: O nome único do seu mod, que será usado na URL da página do mod. Deve ser uma string única e sem espaços. Também, deve ser o mesmo nome que você usou no arquivo `mod.json` do seu mod.
      placeholder: KaikeCarlos.SaveUtils
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Nome do mod
      description: Titulo do seu mod, como você gostaria que aparecesse na página do mod.
      placeholder: Save Anywhere
    validations:
      required: true
  - type: input
    id: repoUrl
    attributes:
      label: URL Repositório GitHub
      description: O link para o repositório do seu mod no GitHub. Deve ser um link direto para o repositório que contém o código do seu mod e releases.
      placeholder: https://github.com/Raicuparta/ow-mod-template
    validations:
      required: true
  - type: dropdown
    id: tags
    validations:
      required: true
    attributes:
      label: Tags
      description: Tags que descrevem o seu mod. Selecione todas as que se aplicam.
      multiple: true
      options:
        - utility
  - type: input
    id: author
    attributes:
      label: Nome do autor
      description: Nome do autor do mod ou dos autores, como você gostaria que aparecesse na página do mod.
      placeholder: Kaike Carlos
  - type: input
    id: description
    attributes:
      label: Mod Description
      description: Coloque a descrição do seu mod aqui.
      placeholder: Um mod que faz coisas legais.